train_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/training.csv"
validation_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/validation.csv"
test_data_dir: "/extra/tom/validation/segmented/testing.csv"

batch_size: 32
learning_rate: 0.001
max_train_steps: 100000

num_train_files: 2187144
num_test_files: 546788

# mel images
mel_image_width: 121 # 1 sec mono audio; automatically calculated: segement_length * 121px
mel_image_height: 40
mel_image_depth: 1

# full size spectrograms
spectrogram_image_width: 100 # 1 sec mono audio; automatically calculated: segement_length * 100px
spectrogram_image_height: 506
spectrogram_image_depth: 1

spectrogram2_image_width: 31 # 1 sec mono audio; automatically calculated: segement_length * 100px
spectrogram2_image_height: 128
spectrogram2_image_depth: 1

image_type: "spectrogram" # "mel" or "spectrogram" or "spectrogram2"
segment_length: 10 # sec

label_names: ["EN", "DE", "FR", "ES"]
num_classes: 4



